"""empty message

Revision ID: 0876571de09f
Revises: 296d08a17086
Create Date: 2022-08-19 16:06:54.050374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0876571de09f'
down_revision = '296d08a17086'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan_im', sa.Column('file', sa.LargeBinary(), nullable=True))
    op.drop_column('scan_im', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan_im', sa.Column('image', sa.BLOB(), nullable=True))
    op.drop_column('scan_im', 'file')
    # ### end Alembic commands ###
