"""empty message

Revision ID: 1d3816fd4066
Revises: e069738acd24
Create Date: 2022-08-08 13:08:48.110092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d3816fd4066'
down_revision = 'e069738acd24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('address', sa.String(length=100), nullable=False))
    op.create_unique_constraint(None, 'users', ['address'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'address')
    # ### end Alembic commands ###
