"""empty message

Revision ID: 296d08a17086
Revises: bff443ce8392
Create Date: 2022-08-18 11:35:48.871606

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '296d08a17086'
down_revision = 'bff443ce8392'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scan_im', 'imagename')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan_im', sa.Column('imagename', mysql.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
