"""empty message

Revision ID: 3bcb61628ea6
Revises: e5f0861abb00
Create Date: 2022-08-15 17:32:53.026226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bcb61628ea6'
down_revision = 'e5f0861abb00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan_im', sa.Column('patient_scan', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'scan_im', 'patient', ['patient_scan'], ['idPatient'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scan_im', type_='foreignkey')
    op.drop_column('scan_im', 'patient_scan')
    # ### end Alembic commands ###
