"""empty message

Revision ID: b6caf1a63b9e
Revises: 0876571de09f
Create Date: 2022-08-20 11:21:06.106857

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b6caf1a63b9e'
down_revision = '0876571de09f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('scan_im_ibfk_1', 'scan_im', type_='foreignkey')
    op.drop_column('scan_im', 'patient_scan')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan_im', sa.Column('patient_scan', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('scan_im_ibfk_1', 'scan_im', 'patient', ['patient_scan'], ['idPatient'])
    # ### end Alembic commands ###
