"""empty message

Revision ID: baa86a83d475
Revises: cb44293e75fe
Create Date: 2022-08-21 15:45:13.358169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baa86a83d475'
down_revision = 'cb44293e75fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan_im', sa.Column('name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scan_im', 'name')
    # ### end Alembic commands ###
