"""empty message

Revision ID: bff443ce8392
Revises: 3bcb61628ea6
Create Date: 2022-08-16 09:42:53.611684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bff443ce8392'
down_revision = '3bcb61628ea6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan_im', sa.Column('image', sa.LargeBinary(), nullable=True))
    op.drop_column('scan_im', 'data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan_im', sa.Column('data', sa.BLOB(), nullable=True))
    op.drop_column('scan_im', 'image')
    # ### end Alembic commands ###
