"""empty message

Revision ID: cb44293e75fe
Revises: b6caf1a63b9e
Create Date: 2022-08-20 11:37:19.971152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb44293e75fe'
down_revision = 'b6caf1a63b9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan_im', sa.Column('patient_scan', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'scan_im', 'patient', ['patient_scan'], ['idPatient'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scan_im', type_='foreignkey')
    op.drop_column('scan_im', 'patient_scan')
    # ### end Alembic commands ###
