"""empty message

Revision ID: e29cef000e43
Revises: e75f0e8c83ab
Create Date: 2022-08-14 10:22:47.043079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e29cef000e43'
down_revision = 'e75f0e8c83ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('address', table_name='users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('address', 'users', ['address'], unique=False)
    # ### end Alembic commands ###
