"""empty message

Revision ID: e3723515e9db
Revises: e29cef000e43
Create Date: 2022-08-15 16:31:29.325063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3723515e9db'
down_revision = 'e29cef000e43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan_im',
    sa.Column('idImage', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('idImage')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scan_im')
    # ### end Alembic commands ###
