"""empty message

Revision ID: e5f0861abb00
Revises: e3723515e9db
Create Date: 2022-08-15 16:32:23.432089

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e5f0861abb00'
down_revision = 'e3723515e9db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan_im', sa.Column('imagename', sa.String(length=50), nullable=True))
    op.add_column('scan_im', sa.Column('data', sa.LargeBinary(), nullable=True))
    op.drop_column('scan_im', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan_im', sa.Column('image', mysql.VARCHAR(length=50), nullable=True))
    op.drop_column('scan_im', 'data')
    op.drop_column('scan_im', 'imagename')
    # ### end Alembic commands ###
