"""empty message

Revision ID: e75f0e8c83ab
Revises: 1d3816fd4066
Create Date: 2022-08-12 12:31:47.536704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e75f0e8c83ab'
down_revision = '1d3816fd4066'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient',
    sa.Column('idPatient', sa.Integer(), nullable=False),
    sa.Column('Full_name', sa.String(length=50), nullable=True),
    sa.Column('Age', sa.String(length=50), nullable=True),
    sa.Column('Phone', sa.String(length=50), nullable=True),
    sa.Column('Nm_Carte', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('idPatient')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patient')
    # ### end Alembic commands ###
